spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    username: baeldung
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=handozhynski
    password: baeldung
  jackson:
    property-naming-strategy: SNAKE_CASE

